### ISSUE TITLE
Invite to Nextcloud Talk instance for chat

### ISSUE THREAD

**Issue by jancborchardt** [cbackas/iOS-Deck#1]
Hi @cbackas, awesome app! :) This is just a meta-issue to tell you that we have a Nextcloud Talk instance where we invite Nextcloud contributors to be able to communicate more quickly, and we also have channels for e.g. "Deck app team" and "Mobile apps".

If you like, I could just give you a guest account via the email address in your commits?

cc our other iOS contributors @ivansss @marinofaggiana @immortal79 @jorisbodin @phedlund to check out this nice app :)

**Comment by cbackas** [comment]
@jancborchardt Thanks for reaching out, I'd definitely appreciate being added

**Comment by cbackas** [comment]
@jancborchardt I haven't used Nextcloud talk before, do I need to install it on my NC instance and do some kinda federation thing or do you have a NC server address I can put into the app on my phone?

**Comment by stefan-niedermann** [comment]
@cbackas no, @jancborchardt will create an account for you. You can then just sign in at [cloud.nextcloud.com](https://cloud.nextcloud.com) and use the talk app there (this is also the NC server address you put into the app on your phone). Just wait for the sign-up-email :slightly_smiling_face:

**Comment by cbackas** [comment]
@stefan-niedermann Great thanks for clearing that up for me. I'll be on the lookout for that email

**Comment by jancborchardt** [comment]
Gave you an account now @cbackas – sorry for the delay, and thanks @stefan-niedermann for adding the explanation. :) Will close this then, see you there or let me know if there’s any issues.

**Comment by rakekniven** [comment]
Hello @cbackas I would gladly be a tester for you. Are you using Testflight?

**Comment by cbackas** [comment]
> 
> 
> Hello @cbackas I would gladly be a tester for you. Are you using Testflight?

Hey @rakekniven, unfortunately the app in its current state isn't ready for any kind of testers... Admittedly I haven't worked on this project in a little bit now as I've been focusing my efforts on trying to find a job. If interviews I've got this next week don't go too well I might be working on this project a bit more :P I'd like to keep working on it a bit in my free time regardless after I get more settled but would also like if anyone wants to help out with the development.

**Comment by jancborchardt** [comment]
cc @jospoortvliet as I'm sure we can get a blog post & some tweets on a call for contributors to the Deck iOS app going? :)

**Comment by rakekniven** [comment]
> but would also like if anyone wants to help out with the development.

I can help you translation and testing. Sorry, no coding.

**Comment by Diskoteket** [comment]
> but would also like if anyone wants to help out with the development

I want to help!

**Comment by Diskoteket** [comment]
@cbackas I would like to schedule a meeting some time after christmas to start working on this project.
Send me an email! tim@wetterek.se
